### ISSUE TITLE
Scrapper is returning null for couple of imdb id

### ISSUE THREAD

**Issue by manishrawat4u** [hack-throne/imdb-scrapper#27]
While using IMDBScraper.scrapper(imdbId) if imdbId is tt4486148 then the scrapper is returning null. 

Internally getSimilarMoviesById function is creating problem. Is there any way to update this function?

**Comment by anshulrgoyal** [comment]
@manishrawat4u you can always create a pull request.

**Comment by manishrawat4u** [comment]
> @manishrawat4u you can always create a pull request.

yes, I did that... easy to fix

**Comment by manishrawat4u** [comment]
https://github.com/hack-throne/imdb-scrapper/pull/30

**Comment by manishrawat4u** [comment]
@anshulrgoyal -any plan of releasing soon to npm?

**Comment by anshulrgoyal** [comment]
Would release in few weeks

**Comment by anshulrgoyal** [comment]
@manishrawat4u released the package.
