### ISSUE TITLE
ADD SUPPORT FOR TV SHOW EPIOSDE SYNOPSIS SUPORT

### ISSUE THREAD

**Issue by anshulgoyal15** [hack-throne/imdb-scrapper#5]
## Description 
Add support for TV show episode synopsis and on AIR date and stars
**Try**  to add new function with appropriate name and tests

**Comment by vkolova** [comment]
I'd like to work on that

**Comment by anshulgoyal15** [comment]
Ok no problem we are extremely fast in replying and reviewing PRS and thanks in advance
