### ISSUE TITLE
Add Support to scrap Stars and different celebs from imdb

### ISSUE THREAD

**Issue by anshulgoyal15** [hack-throne/imdb-scrapper#6]
This can be achieved by scrapping ```https://www.imdb.com/name/nm0897201/?ref_=tt_cl_t1```
the **nm0897201** is the id of the star the function could be give a id of star and it will give the details and it would be great if we could a search function for star it can be done by scrapping ```https://www.imdb.com/find?ref_=nv_sr_fn&q=vijay&s=nm``` where **vijay** is the star name and **nm**
is catagory

**Comment by 0c0de** [comment]
Hello I'll do this :smile:

**Comment by anshulgoyal15** [comment]
Ok no problems .Best of luck and thanks in advance.

**Comment by 0c0de** [comment]
Job is done :sunglasses:

**Comment by anshulgoyal15** [comment]
hi requested a few changes

**Comment by 0c0de** [comment]
Ok I've seen it now
