### ISSUE TITLE
Add support for Today born star 

### ISSUE THREAD

**Issue by anshulgoyal15** [hack-throne/imdb-scrapper#8]
This can be achieved by scrapping this URL ```https://www.imdb.com/search/name?birth_monthday=10-02&refine=birth_monthday&ref_=nv_cel_brn``` **10-2** is the date and the function can take optional date to give the birth day on that day and the format .Moment can be used to parse the date and formed in the required format

**Comment by masquel** [comment]
Hi, I'll take it.

**Comment by anshulgoyal15** [comment]
ok no problem .Best of luck.Thanks in advance .
